### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by ananyakaushik48** [basir/next-amazona#17]
Sir please look into this issue its been unresolved for a while, I can't locate the source of the issue.
![Screenshot_2022-06-24_00_21_22](https://user-images.githubusercontent.com/30756155/175375687-af0eebc1-7826-4eb4-9792-252b15038f31.png)
![Screenshot_2022-06-24_00_21_29](https://user-images.githubusercontent.com/30756155/175375698-065d4320-a829-4b0b-8dfd-31fde8ef86ad.png)
![Screenshot_2022-06-24_00_21_32](https://user-images.githubusercontent.com/30756155/175375707-598a299f-c426-442f-b8bf-08c360b9c433.png)

**Comment by AharrFaris** [comment]
Try removing `import db from './db';` from **utils/error.js**!

**Comment by AharrFaris** [comment]
Try removing `import db from './db';` and `await db.disconnect();` from **utils/error.js**!

**Comment by ananyakaushik48** [comment]
That worked for me thanks
