### ISSUE TITLE
Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by IlirBajrami** [basir/next-amazona#2]
I'm having the `SyntaxError: Unexpected token o in JSON at position 1` when saving the `userInfo` to Cookie.
The Cookie value is `[object%Object]`

![Screenshot 2021-09-01 at 12 34 43](https://user-images.githubusercontent.com/22265824/131657036-347e3066-080d-42fa-96cc-56ef2f81b0d8.png)

What am i doing wrong?

**Comment by IlirBajrami** [comment]
i fixed this by adding `JSON.stringify` to user `data` like this:

`const submitHandler = async (e) => {
    e.preventDefault();
    try {
      const { data } = await axios.post("/api/users/login", {
        email,
        password,
      });
      dispatch({ type: "USER_LOGIN", payload: data });
      Cookies.set("userInfo", JSON.stringify(data)); // <------- JSON.stringify added here
      router.push(redirect || "/");
    } catch (err) {
      alert(err.response.data ? err.response.data.message : err.message);
    }
  };`
Is this the right way?

**Comment by MiladArdehali** [comment]
Yes @IlirBajrami, 
This is the right solution 👍

**Comment by IlirBajrami** [comment]
Ok, thanks!

**Comment by chriswch** [comment]
The same issue is in pages/register.js.
`JSON.stringify()` should be added to user `data` in `Cookies.set()`.
